//! Deliberately absurd hardware/OS names fed to trackers and data brokers
//! instead of the user's real device profile. The goal isn't to blend into
//! a crowd of "normal" browsers — it's to make every fingerprinting vendor's
//! dataset a little more useless by filling it with things that were never,
//! could never be, and will never be a real end-user device.
//!
//! The wilder and more thematically inconsistent, the better: a data broker
//! correlating "M1A2 Abrams Tank Fire Control System" with "TempleOS" with
//! "Urna Eletronica Brasileira" across sessions is not building a coherent
//! advertising profile of anyone.

pub const CHAOS_HARDWARES: &[&str] = &[
    // Military & Defense
    "LGM-30 Minuteman III Vector-Thrust Array",
    "U.S. government Aircraft Air Force One Avionics",
    "Ohio-class Ballistic Missile Submarine SSBN-726",
    "AN/FSQ-7 Combat Direction Central",
    "M1A2 Abrams Tank Fire Control System v4",
    "MQ-9 Reaper UAV Ground Control Station",
    "Patriot PAC-3 Missile Battery Radar Node",
    "Iron Dome Tamir Interceptor Guidance Unit",
    "B-2 Spirit Stealth Bomber Mission Computer",
    "AEGIS Combat System Mk 7 Baseline 9",
    "Trident II D5 Reentry Vehicle Bus Controller",
    "NORAD Cheyenne Mountain Threat Assessment Node",
    "SR-71 Blackbird Astro-Inertial Navigation System",
    "Phalanx CIWS Mk 15 Fire Control Radar",
    // Aerospace & Exploration
    "SpaceX Satellite Starlink G17-48",
    "Voyager 1 Deep Space Probe (Decel-Phase)",
    "International Space Station ISS Nauka Module",
    "James Webb Space Telescope ISIM Core",
    "Apollo 11 Guidance Computer (AGC) Silicon Replica",
    "Mars Rover Perseverance Sample Caching System",
    "Hubble Space Telescope Fine Guidance Sensor",
    "Cassini-Huygens Radioisotope Thermoelectric Generator",
    "New Horizons Pluto Flyby Data Recorder",
    "Soyuz MS-22 Descent Module Avionics",
    "Boeing Starliner CST-100 Flight Computer",
    "Chang'e 5 Lunar Ascent Vehicle Controller",
    // Home Appliances & Vague IoT
    "Brastemp Microwave Matrix-Display v4.2",
    "Electrolux Smart Twin-Cooling Fridge System",
    "Arno Turbo Force Bluetooth Fan Controller",
    "Philips Walita AirFryer Smart-Crisp Module",
    "Thermomix TM6 Overclocked Induction Core",
    "Britânia Liquidificador Turbo IoT Edition",
    "Consul Facilite Smart Washer Cycle Engine",
    "Nespresso Vertuo Cloud-Connected Brew Unit",
    "iRobot Roomba j9+ Terrain Mapping ASIC",
    "Samsung Family Hub Refrigerator Display Node",
    "Mondial Grill Inox Wi-Fi Temperature Sensor",
    // Nostalgia & Historical Hardware
    "Nokia 3310 Monolithic Hardware Layer",
    "Tamagotchi Connection v3 (Bandai-1994)",
    "Game Boy Color (CPU LR35902 @ 8.388 MHz)",
    "Commodore 64 MOS Technology 6510 Array",
    "IBM System/360 Model 91 Mainframe",
    "Urna Eletronica Brasileira Modelo UE2026",
    "ZX Spectrum 48k Rubber-Key Logic Board",
    "Atari 2600 TIA Graphics Coprocessor",
    "Palm Pilot 5000 Graffiti Input Controller",
    "Sega Dreamcast VMU Save-State Chip",
    "Motorola StarTAC Analog Baseband Modem",
    "Amiga 500 Copper/Blitter Coprocessor Pair",
    "Speak & Spell TI TMC0280 Speech Synthesizer",
    "Minitel 1B French Videotex Terminal",
    // Transhumanism & Biology
    "Human Nervous System via Neuralink BCI v0.8-beta",
    "Cyberdyne Systems T-800 CPU Architecture",
    "Weyland-Yutani Synthetic Cognition Substrate",
    "Ghost in the Shell Cyberbrain Firewall Module",
    "DARPA Hand Proprioceptive Feedback Array",
    // Industrial & Infrastructure
    "Itaipu Binacional Turbine Governor Controller",
    "Three Gorges Dam SCADA Master Node",
    "Large Hadron Collider Cryogenic Control System",
    "Chernobyl RBMK-1000 Reactor Control Rod Array (Pre-1986)",
    "Boeing 747-8 FADEC Engine Controller",
    "Deepwater Horizon Blowout Preventer Stack",
    "Panama Canal Miraflores Lock Gate Actuator",
    "CERN ATLAS Detector Trigger System",
    // Medical
    "Da Vinci Xi Surgical Robot Arm Controller",
    "GE Revolution CT Scanner Gantry Processor",
    "Abiomed Impella Heart Pump Firmware Node",
    "Philips MRI 3T Gradient Coil Driver",
    "Pacemaker Medtronic Azure XT Telemetry Chip",
    // Automotive & Transportation
    "Tesla Full Self-Driving HW4 Vision Cluster",
    "Shinkansen N700S Traction Control Unit",
    "Fórmula 1 Ferrari SF-26 ECU Ken Block Edition",
    "Boeing CH-47 Chinook Flight Management System",
    "Maersk Triple-E Class Container Ship Bridge Console",
    // Entertainment & Arcade
    "Pac-Man Namco Galaxian Arcade PCB (1980)",
    "DDR (Dance Dance Revolution) Pad Sensor Array",
    "Jukebox Wurlitzer 1015 Vacuum-Tube Amplifier",
    "Pinball Williams Addams Family Solenoid Driver",
    "Laserdisc Pioneer LD-V8000 Player Controller",
    // Crypto, Finance & Banking
    "Bitcoin ASIC Antminer S21 Hydro Mining Rig",
    "NYSE Matching Engine Order-Book FPGA",
    "SWIFT MT103 Message Routing Appliance",
    "Bloomberg Terminal B-Unit Keyboard Controller",
    "Federal Reserve Fedwire Settlement Node",
    // Naval & Espionage
    "U-2 Dragon Lady Optical Bar Camera System",
    "GCHQ TEMPORA Deep Packet Inspection Array",
    "Enigma Machine Rotor Wiring Board (Replica)",
    "Cold War SOSUS Hydrophone Array Node",
    "Zumwalt-class Destroyer Integrated Power System",
    // Absurd Brazilian Institutions
    "Correios SEDEX Rastreamento Central Mainframe",
    "DETRAN CNH Digital Biometric Reader v2",
    "Receita Federal Malha Fina Processing Cluster",
    "Metro-SP Linha 4-Amarela Signaling Backbone",
    // Fiction & Mockery
    "Skynet Global Defense Network Core OS Terminal",
    "HAL 9000 Logic Memory System Interface",
    "The Matrix Architect Mainframe Console",
    "Wall-E Directive Compliance Processing Unit",
    "Portal Aperture Science GLaDOS Neural Core",
    "Jurassic Park InGen Nedry Backdoor Terminal",
];

pub const CHAOS_OPERATING_SYSTEMS: &[&str] = &[
    // Cryptography & Historical Military
    "OS: Enigma v1945 TI Fuhrer Special Edition",
    "Strategic Air Command Command-Line (SAC-OS)",
    "KGB Krypteria OS v1984.3",
    "Pentagon Joint Worldwide Intelligence Communications System (JWICS-OS)",
    "NSA ECHELON Signal Triage OS build 7",
    "Stasi Zentrale Aktenverwaltung OS v1971",
    "Bletchley Park Colossus Valve-Logic Control OS",
    // Digital Dinosaurs (Completely Web-Incompatible)
    "MS-DOS 6.22 w/ Windows 3.11 for Workgroups",
    "Windows 95 Second Edition (OSR2.5) build 1214",
    "Windows 98 SE Plus! Pack (Active Desktop Enabled)",
    "OS/2 Warp v4.52 (Merlin Convenience Pack)",
    "AmigaOS 3.9 (Workbench build 45.57)",
    "TempleOS v5.03 Public Domain",
    "Windows Me Millennium Edition (Unpatched)",
    "BeOS R5 Personal Edition (Dual-CPU Demo)",
    "GEOS 2.0 for Commodore 64",
    "Windows NT 3.51 Workstation SP5",
    // Absurd & Embedded Unix/Linux
    "Linux 0.01 (Linus Torvalds Original Hand-Coded)",
    "Red Hat Linux 5.2 (Apollo) Kernel 2.0.36",
    "FreeBSD 1.0 (EPSILON) Release 1993",
    "Cisco IOS v12.2(4)T Enterprise Base",
    "Symbian OS v7.0s UIQ 2.1",
    "BlackBerry OS v4.5.0 Carrier-Locked",
    "Plan 9 from Bell Labs (Fourth Edition)",
    "MINIX 3.1.0 Reliability-Focused Build",
    "QNX Neutrino RTOS 6.3.2 (Automotive Cluster)",
    "VxWorks 5.5 (Mars Pathfinder Flight Build)",
    "Solaris 2.6 SPARCstation Edition",
    "IRIX 6.5.30 (SGI Onyx2 Workstation)",
    // Defunct & Forgotten Corporate
    "Novell NetWare 3.12 IPX/SPX Server",
    "Lotus Notes/Domino R5 Enterprise Client",
    "WordPerfect Office 2000 Suite Runtime",
    "Banyan VINES 5.5 Enterprise Network OS",
    "Sun Microsystems JavaStation NC OS",
    "Xerox Star 8010 Information System (1981)",
    // Soviet & Eastern Bloc
    "Elektronika BK-0010 Soviet Home Computer OS",
    "Agat-7 Soviet Apple II Clone DOS",
    "MSX2 Yamaha Eastern Bloc Localized Build",
    "PC/M East German Robotron A7100 OS",
    // Archaic Banking & Bureaucracy
    "COBOL Mainframe Batch-Job Scheduler OS/390",
    "IBM CICS Transaction Server v3.1 Terminal",
    "Detran-SP Sistema Nacional CNH Legacy Terminal",
    "SERPRO Receita Federal Malha-Fina Batch OS",
    "Bradesco Terminal Bancário COBOL 1998",
    // Fiction & Mockery
    "Skynet Global Defense Network Core OS v2.04",
    "HAL 9000 Logic Memory System OS",
    "Windows Vista Ultimate Service Pack 3 (Unreleased)",
    "Matrix Digital Rain Decoder OS v0.1",
    "GLaDOS Aperture Science Neurotoxin Scheduler",
    "Wintermute Cyberspace Construct OS (Neuromancer)",
    "Master Control Program (TRON, 1982 Build)",
    "Jurassic Park InGen UNIX 4.0.3 (\"It's a Unix system!\")",
    "Weyland-Yutani MU/TH/UR 6000 Interface",
    "Terminator Cyberdyne Systems Model 101 Firmware",
    // Absurd Local & Regional Institutions
    "Urna Eletronica Brasileira TSE OS v2026.1",
    "Correios SEDEX Tracking Terminal DOS Edition",
    "CPTM Linha 11-Coral Signaling Control OS",
    "Junta Comercial Estadual Sistema Legado v3",
];
